version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "sam-app-test"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-12w6epzqunihl"
s3_prefix = "sam-app-test"
region = "ap-southeast-2"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
parameter_overrides = "SNSEndpoint=\"damianzm@amazon.com\""
image_repositories = []
